- name: Core apps install
  apt:
    name: 
      - guake
      - neofetch
      - figlet
      - flatpak
      - zsh
      - tldr
      - eza
      - git
      - nala
      - ffmpeg
      - yt-dlp
      - conky
      - gnome-tweaks
      - vlc
    state: latest
    update_cache: true
  become: true
